spring:
  application:
    name: products-shop-elasticsearch

  datasource:
    url: jdbc:postgresql://localhost:5432/techstore_db
    username: postgres
    password: YOUR_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: YOUR_PASSWORD
    connection-timeout: 1000
    socket-timeout: 30000

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC

  webclient:
    connect-timeout: 5000
    read-timeout: 10000

  elasticsearch-client:
    host: localhost
    port: 9200
    username: elastic
    password: changeme
    protocol: http

  server:
    port: 8080
    servlet:
      context-path: /api
    error:
      include-message: always
      include-binding-errors: always
