spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/techstore_db
    username: postgres
    password: YOUR_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  elasticsearch:
    uris: http://elasticsearch:9200
    username: elastic
    password: changeme
    connection-timeout: 5000
    socket-timeout: 60000

  elasticsearch-client:
    host: elasticsearch
    port: 9200
    username: elastic
    password: changeme
    protocol: http

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC

  webclient:
    connect-timeout: 5000
    read-timeout: 10000

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
